name: Android CI/CD Library

on:
  push:
    branches: [ "feature/add-cicd-android-library" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew :appambit-sdk:assembleRelease
      
    - name: Upload AAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: appambit-sdk-release
        path: appambit-sdk/build/outputs/aar/appambit-sdk-release.aar
